apiVersion: v1
kind: ConfigMap
metadata:
  name: system-info-config
  namespace: system-info
  labels:
    app: system-info-api
data:
  ENVIRONMENT: "production"
  APP_NAME: "system-info-api"
  FLASK_ENV: "production"
